### ISSUE TITLE
GraphIterator discrepency

### ISSUE THREAD

**Issue by mbhall88** [GATB/gatb-core-tuto#2]
At line 31 of [GATB Tutorial lesson 2: iterate over the nodes of a De Bruijn graph](http://gatb-core.gforge.inria.fr/training/gatb-compiler.html?snippet=debruijn6) an iterator over the nodes in a graph is declared with

```c++
Graph::Iterator<Node> it = graph.iterator ();
```

This compiles and runs on the online tutorial ok but I noticed it didn't work on my local machine.  

After looking into the documentation though it appears the correct syntax should have been

```c++
GraphIterator<Node> it = graph.iterator ();
```

This declaration works on my local machine.  

I just thought I would flag this and maybe you could clear up why there is a difference?  

PS. Thank you for the tutorials. They have been incredibly helpful! 👍

**Comment by rchikhi** [comment]
thanks for letting us know! There are indeed some small API differences between tutorial versions and the GATB Tutorial website is still on an older version. When we make the version switch, we'll update all tutorial examples. (but it's a bit of work)
